### PR TITLE
Fix reveal and add tests

### LINKED ISSUE #275: Fix reveal component
Reveal’s hard hidden on page load with `.is-hidden` class on the wrong element.

It looks like [the reveal](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-reveal) does not have a unit test and has a breaking change with 0.10.2

In the documentation, the entire reveal component is incorrectly hidden on page load, when it should only be hiding the additional details.

### PR DESCRIPTION
**Pull request by coltborg**
# What does this PR do?

- Changes reveal class `is-hidden` to `is-hiding-content`
- Adds a test suite for the reveal component
- Closes #275

### CODE REVIEW

File: spec/system/reveal_spec.rb [hunk 1]
```diff
@@ -0,0 +1,31 @@
+require "spec_helper"
+
+describe "Reveal" do
+  before do
+    visit "cfa/styleguide/examples/molecules/reveal"
+  end
+
+  describe "default view" do
+    it "on page load, trigger is visible and content is not", js: true do
+      expect(page).to have_content "Learn more about student eligibility"
```
Comment (bengolder) [inline spec/system/reveal_spec.rb:10]: add an additional assertion about not showing the content

**Review by bengolder — APPROVED** [review]
Looks good!
